Dev/online
pennmem/Courier pull request #5
Opened 2021-10-15 20:23 UTC by leo950804

2021-10-15 22:07 UTC, bruskajp requested changes

2021-10-15 22:07 UTC, bruskajp commented on Assets/NiclsInterface/NiclsInterface3.cs
> +#endif
For endif, it is good coding practice to put a comment describing what you are ending.
#endif  // UNITY_STANDALONE

2021-10-15 22:07 UTC, bruskajp commented on Assets/Scripts/CoroutineExperiment.cs
> +    #if UNITY_STANDALONE
Why are you commenting this out in the Delivery code? Shouldn't this be just commented out in SoundRecorder class itself?

2021-10-15 22:07 UTC, bruskajp commented on Assets/Scripts/CoroutineExperiment.cs
> +    protected IEnumerator GetOnlineConfig()
This should be a part of FlexibleConfig?
Even better, this should be a part of GetConfig such that the code doesn't have to change in other places.

2021-10-15 22:07 UTC, bruskajp commented on Assets/Scripts/DeliveryItems.cs
> +        #if UNITY_STANDALONE
why is this different?

2021-10-15 22:07 UTC, bruskajp commented on Assets/Scripts/DeliveryItems.cs
> +        #if UNITY_STANDALONE
Why can't this logic go into those above functions?

2021-10-15 22:07 UTC, bruskajp commented on Assets/Scripts/FlexibleConfig.cs
> +    private static object GetSetting(string setting)
This may be better as a Templated type, but this works in practice

2021-10-15 22:07 UTC, bruskajp commented on Assets/Scripts/PlayerMovement.cs
> +
What is this for?

2021-10-15 22:07 UTC, bruskajp commented on Assets/UnityEPL/Prefabs/VideoPlayer/VideoControl.cs
> +        if (videoPlayer.time >= videoPlayer.clip.length) // videoPlayer.clip.length
indentation

2021-10-15 22:07 UTC, bruskajp commented on Assets/UnityEPL/Scripts/DataPoint.cs
> +    private System.Collections.Generic.Dictionary<string, object> dataDict;
Why was the name expanded everywhere here?

2021-10-15 22:07 UTC, bruskajp commented on Assets/UnityEPL/Scripts/DataPoint.cs
> +        else
why is "else if" split onto 2 lines?

2021-10-18 15:35 UTC, woohyeuk-leo-chang commented on Assets/Scripts/CoroutineExperiment.cs
> +    protected IEnumerator GetOnlineConfig()
To my knowledge, UnityWebRequest should be under monobehaviour. 
That was why I wrote this under CoroutineExperiment.

2021-10-18 15:45 UTC, leo950804 commented on Assets/Scripts/DeliveryItems.cs
> +        #if UNITY_STANDALONE
Because they are all writing to files?
Also, I feel like online version doesn't need any of these functions.

2021-10-18 15:59 UTC, woohyeuk-leo-chang commented on Assets/Scripts/PlayerMovement.cs
> +
It was my attempt to reset the player's position after FPS testing where they should navigate around the town

2021-10-20 14:40 UTC, bruskajp commented on Assets/Scripts/PlayerMovement.cs
> +
cool. Works for me. Was just wondering why it was needed.

2021-10-20 15:04 UTC, bruskajp commented on Assets/Scripts/CoroutineExperiment.cs
> +    protected IEnumerator GetOnlineConfig()
I mean, it needs to be used in a coroutine, but this means that it can be called from any IEnumerator function. This is not entirely the setup of the current config.

I am inclined to say that it should still be put in the FlexibleConfig file as a result. As for calling GetConfig in the other Config code, you're right, that probably won't work well. This will likely be a problem for me in the future when I want to convert it, but this is not you're problem.

2021-11-05 15:20 UTC, bruskajp commented on Assets/Scripts/FlexibleConfig.cs
>              string configPath = System.IO.Path.Combine(
Can you indent these lines?

2021-11-05 18:26 UTC, bruskajp approved these changes

2021-11-05 18:26 UTC, merged